version: '3.5'
services:
#  es:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#    container_name: es
#    environment:
#      - discovery.type=single-node
#    ports:
#      - 9200:9200
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
  web:
    build: .
    ports: 
    - "8000:8000"
    volumes:
      - "./TCRpdbTools:/opt/app"
    container_name: TCRpdbTools
    restart: unless-stopped
    command: bash -c '(gunicorn TCRpdbTools.wsgi --user www-data --bind 0.0.0.0:8010 --workers 3) & nginx -g "daemon off;"'
